"""Host roster and per-host materializers for multi-host installs.

A project's `.compass/meta/plugin.yaml` may carry a `hosts:` list naming
every agent CLI the project uses (`claude-code`, `dsh`, ...). A plugin.yaml
without the field means `[claude-code]`, so every install that predates the
roster behaves exactly as before. `self_update._apply` refreshes every
rostered host in one run - the invariant that no two hosts of one project
can sit on different Compass versions (SPEC-006 D-04).

The dsh materializer generates `.dsh/hooks.json` from the canonical hook
manifest. dsh executes hooks through PowerShell on Windows, so the sh
wrapper (`if command -v python3 ...`) is reduced to the dialect-neutral
form `python "${CLAUDE_PROJECT_DIR}/..."`: dsh substitutes the `${...}`
token at parse time, and a POSIX shell reads the same token as an env-var
expansion. Events dsh's bridge does not parse and `if` fields (Claude Code
permission-pattern syntax) are dropped from the generated file.
"""

import json
import re
from pathlib import Path

import vaultlib

DEFAULT_HOSTS = ["claude-code"]

# The events dsh's hooks-claude-code bridge parses
# (deepseek-harness packages/hooks/hooks-claude-code/src/config.ts).
DSH_EVENTS = {
    "SessionStart",
    "UserPromptSubmit",
    "PreToolUse",
    "PostToolUse",
    "Stop",
    "SubagentStart",
    "SubagentStop",
}

# plugin.yaml nests its fields under a `plugin:` mapping, so the field is
# usually indented; a top-level `hosts:` is accepted too.
_HOSTS_LINE = re.compile(r"^[ \t]*hosts:\s*(\[.*\])\s*$", re.MULTILINE)

# The manifest's sh wrapper: `if command -v python3 ...; then python3 X; else python X; fi`.
# The python3 branch carries the invocation to keep.
_SH_WRAPPER = re.compile(r"^if command -v python3.*?then\s+python3\s+(.*?);\s*else.*fi$")


def read_hosts(vault_root):
    """The project's host roster from plugin.yaml; `[claude-code]` when the
    file or the field is absent. Unknown names pass through verbatim so a
    newer roster read by an older CLI is never silently narrowed."""
    path = Path(vault_root) / "meta" / "plugin.yaml"
    if not path.is_file():
        return list(DEFAULT_HOSTS)
    match = _HOSTS_LINE.search(vaultlib.read_vault_text(path))
    if not match:
        return list(DEFAULT_HOSTS)
    hosts = vaultlib._split_inline_list(match.group(1)[1:-1])
    return [h for h in hosts if h] or list(DEFAULT_HOSTS)


def _neutral_command(command):
    """The dialect-neutral form of a manifest hook command: the sh
    python3/python fallback wrapper reduces to a bare `python` invocation
    with the `${CLAUDE_PROJECT_DIR}` token kept for parse-time
    substitution. A command that carries no wrapper passes through."""
    match = _SH_WRAPPER.match(command.strip())
    if match:
        command = "python " + match.group(1)
    return command.replace('"$CLAUDE_PROJECT_DIR', '"${CLAUDE_PROJECT_DIR}')


def materialize_dsh_hooks(project_root, manifest_path):
    """Generate `.dsh/hooks.json` for `project_root` from the canonical
    manifest. Returns the path written."""
    manifest = json.loads(Path(manifest_path).read_text(encoding="utf-8"))
    hooks = {}
    for event, groups in manifest.get("hooks", {}).items():
        if event not in DSH_EVENTS:
            continue
        out_groups = []
        for group in groups:
            cleaned = {k: v for k, v in group.items() if k != "hooks"}
            cleaned["hooks"] = [
                {**{k: v for k, v in h.items() if k != "if"},
                 "command": _neutral_command(h["command"])}
                for h in group.get("hooks", [])
            ]
            out_groups.append(cleaned)
        hooks[event] = out_groups
    dest = Path(project_root) / ".dsh" / "hooks.json"
    dest.parent.mkdir(parents=True, exist_ok=True)
    vaultlib.write_text_lf(dest, json.dumps({
        "description": (
            "Generated by compass from the canonical hook manifest for the "
            "dsh host. Do not hand-edit; self-update regenerates it."
        ),
        "hooks": hooks,
    }, indent=2) + "\n")
    return dest
