"""Catalog row reader and ranking for `compass lessons`.

Reads `.compass/meta/lessons-catalog.yaml` rows only, never lesson bodies.
The catalog is machine-generated by `compass sync` (`commands/sync.py`,
`_catalog_row`) with a fixed row shape: a `- file: "<name>"` line followed
by `status`, `category`, `area`, `tags` (an inline `[a, b]` list), `score`
(an integer), and `summary`, each indented four spaces. A row may also
carry `escalated`, written by `_catalog_row` for a lesson whose frontmatter
has it and stamped onto an existing row by `lesson-write` at escalation
time (sync appends rows but never rewrites existing ones).
The parser mirrors this shape exactly and fails loud - naming the row
number - on a row that does not match it, rather than silently returning a
short list.

Ranking has no graph substrate: lesson rows carry no `depends_on` or
wikilink edges (SPEC-012 D-04), so retrieval is tag overlap, area match,
and summary-token overlap over the flat row list, with `score` as the
final tiebreak. A row carrying `escalated` always sorts first: escalation
means retrieval already missed or a reader already rejected the lesson
three times, which is the failure this design surfaces rather than hides.
"""

import re
from pathlib import Path

# A row starts with `  - file: "<name>"`; every other field of that row is
# `    <key>: <value>`, one level deeper. This is the exact shape
# `commands/sync.py:_catalog_row` writes.
ROW_START = re.compile(r'^  - file:\s*(.+)$')
FIELD = re.compile(r'^    ([A-Za-z0-9_]+):\s*(.*)$')

REQUIRED_FIELDS = ("status", "category", "area", "tags", "score", "summary")

_WORD = re.compile(r"[a-z0-9]+")


class MalformedRow(Exception):
    """A catalog row missing a required field or carrying a value the
    writer's fixed shape never produces. `row_number` is the row's 1-based
    position among the catalog's lesson entries, in file order."""

    def __init__(self, row_number, reason):
        self.row_number = row_number
        self.reason = reason
        super().__init__(f"row {row_number}: {reason}")


def catalog_path(vault_root):
    return Path(vault_root) / "meta" / "lessons-catalog.yaml"


def _unquote(value):
    """Strip a matching quote layer with YAML unescaping - the inverse of
    the `vaultlib.yaml_double_quote` form `_catalog_row` writes."""
    value = value.strip()
    if len(value) >= 2 and value[0] in "\"'" and value[-1] == value[0]:
        inner = value[1:-1]
        if value[0] == "'":
            return inner.replace("''", "'")
        return re.sub(r'\\(["\\])', r"\1", inner)
    return value


def _parse_tags(value):
    """Parse an inline `[a, b, c]` tag list. Returns `None` when `value` is
    not bracketed - the shape `_catalog_row` always writes - rather than
    guessing at some other list syntax."""
    value = value.strip()
    if not (value.startswith("[") and value.endswith("]")):
        return None
    inner = value[1:-1].strip()
    if not inner:
        return []
    return [_unquote(item) for item in inner.split(",")]


def _finalize(entry):
    row_number = entry["_row"]
    if not entry.get("file", "").strip():
        raise MalformedRow(row_number, "missing file")
    missing = [
        name for name in REQUIRED_FIELDS
        if name not in entry or entry[name].strip() == ""
    ]
    if missing:
        raise MalformedRow(row_number, f"missing field(s): {', '.join(missing)}")
    tags = _parse_tags(entry["tags"])
    if tags is None:
        raise MalformedRow(row_number, f"tags is not a bracketed list: {entry['tags']!r}")
    try:
        score = int(entry["score"].strip())
    except ValueError:
        raise MalformedRow(row_number, f"score is not an integer: {entry['score']!r}")
    return {
        "file": _unquote(entry["file"]),
        "status": _unquote(entry["status"]),
        "category": _unquote(entry["category"]),
        "area": _unquote(entry["area"]),
        "tags": tags,
        "score": score,
        "summary": _unquote(entry["summary"]),
        "escalated": bool(entry.get("escalated", "").strip()),
    }


def parse_catalog(text):
    """Parse every lesson row in catalog `text`. Returns a list of dicts,
    one per row in file order, each holding `file`, `status`, `category`,
    `area`, `tags` (list), `score` (int), `summary`, and `escalated`
    (bool).

    Raises `MalformedRow` on the first row missing a required field, an
    unparseable `tags` list, or a non-integer `score`. Lines outside a row
    block (the `lessons:` header, blank lines, cap-warning comments) are
    ignored.
    """
    rows = []
    current = None
    row_number = 0
    for line in text.splitlines():
        start = ROW_START.match(line)
        if start:
            if current is not None:
                rows.append(_finalize(current))
            row_number += 1
            current = {"file": start.group(1), "_row": row_number}
            continue
        field = FIELD.match(line) if current is not None else None
        if field:
            current[field.group(1)] = field.group(2)
            continue
        if current is not None:
            rows.append(_finalize(current))
            current = None
    if current is not None:
        rows.append(_finalize(current))
    return rows


def load_catalog(vault_root):
    """Load and parse the lessons catalog. Returns the list of row dicts.

    Raises `FileNotFoundError` when the catalog file is absent - a
    malformed vault, not an empty one - and `MalformedRow` on the first row
    whose shape does not match the writer's fixed format.
    """
    path = catalog_path(vault_root)
    if not path.is_file():
        raise FileNotFoundError(str(path))
    return parse_catalog(path.read_text(encoding="utf-8"))


def _tokens(text):
    return set(_WORD.findall((text or "").lower()))


def rank(rows, area=None, tags=None, text=None):
    """Rank the catalog's active (non-archived) rows against a query.

    `tags` is an iterable of query tags, matched against each row's tags
    after lowering both sides - the catalog's own tags are already
    lowercase, so this only widens matching to a query typed in another
    case, never blurs two catalog tags that differ only by case. `area` is
    matched the same way against each row's `area`. `text` is free text,
    matched by token overlap against each row's `summary`.

    Returns rows in ranked order, each carrying `tag_overlap`,
    `area_match` (0 or 1), `text_overlap`, and `rank` (1-based) alongside
    its original fields. Sort key, highest priority first: any row with
    `escalated` set sorts before every row without it, regardless of the
    scores below; then tag overlap; then area match; then text overlap;
    then `score` as the final tiebreak; then `file` for a deterministic
    order among rows tied on everything else.

    When the query carries any criteria, a row matching none of them is
    excluded rather than kept as low-ranked backfill - surfacing an
    unrelated lesson as "relevant" is noise, and the retrieval trace
    records what this returns as surfaced. Escalated rows are exempt from
    the exclusion. A query with no criteria at all is a browse: every
    active row is returned ranked.
    """
    query_tags = {t.strip().lower() for t in (tags or []) if t.strip()}
    query_area = (area or "").strip().lower()
    query_tokens = _tokens(text) if text else set()
    has_criteria = bool(query_tags or query_area or query_tokens)

    scored = []
    for row in rows:
        if row.get("status") == "archived":
            continue
        row_tags = {t.lower() for t in row["tags"]}
        tag_overlap = len(query_tags & row_tags)
        area_match = 1 if query_area and row["area"].lower() == query_area else 0
        text_overlap = len(query_tokens & _tokens(row["summary"])) if query_tokens else 0
        scored.append({
            **row,
            "tag_overlap": tag_overlap,
            "area_match": area_match,
            "text_overlap": text_overlap,
        })

    if has_criteria:
        scored = [
            r for r in scored
            if r["escalated"] or r["tag_overlap"] or r["area_match"] or r["text_overlap"]
        ]

    scored.sort(
        key=lambda r: (
            0 if r["escalated"] else 1,
            -r["tag_overlap"],
            -r["area_match"],
            -r["text_overlap"],
            -r["score"],
            r["file"],
        )
    )
    for i, row in enumerate(scored, start=1):
        row["rank"] = i
    return scored
