"""`compass usage` - the per-command invocation record and its report (ADR-017).

`maincli.dispatch` calls `record()` on every invocation, so the record is
harness-owned bookkeeping: command name, count, and last date land in
`.compass/meta/usage.yaml`, with a `since:` stamp written once so a zero
means "never in the measured window", not "unknown". Recording never raises,
never touches an exit code, skips silently outside a vault, and rewrites a
corrupt record file rather than dying on it - the command being measured
must never pay for the measurement.

The report separates three groups: hook-fired entry points (their counts
measure the harness, not judgment), judgment-invoked commands, and NEVER
USED - zero-count commands listed explicitly, because the visible zero is
the observable miss SPEC-017 exists to create. A dead capability shows up
here as a name with a zero next to it instead of waiting for a human to
notice a symptom.
"""

import datetime
import re
import sys

import vaultlib

RECORD_FILE = "meta/usage.yaml"

# Entry points invoked by hooks rather than by an agent's judgment; the
# report separates them so harness traffic does not read as adoption.
HOOK_COMMANDS = {"sync", "capture-check", "capture-signal", "capture-worker", "self-update"}

ROW = re.compile(r"^  ([A-Za-z0-9_-]+):\s*$")
FIELD = re.compile(r"^    (count|last):\s*(\S+)\s*$")
SINCE = re.compile(r"^since:\s*(\S+)\s*$")


def _parse(text):
    """Return (since, {command: {count, last}}). Tolerates any garbage by
    returning what parsed; a wholly corrupt file parses as empty."""
    since = None
    rows = {}
    current = None
    for line in text.split("\n"):
        m = SINCE.match(line)
        if m:
            since = m.group(1)
            continue
        m = ROW.match(line)
        if m:
            current = m.group(1)
            rows[current] = {"count": 0, "last": ""}
            continue
        m = FIELD.match(line) if current else None
        if m:
            key, value = m.groups()
            if key == "count":
                try:
                    rows[current]["count"] = int(value)
                except ValueError:
                    rows[current]["count"] = 0
            else:
                rows[current]["last"] = value
    return since, rows


def _render(since, rows):
    lines = [
        "# Generated by compass; per-command invocation record (ADR-017).",
        f"since: {since}",
        "usage:",
    ]
    for name in sorted(rows):
        lines.append(f"  {name}:")
        lines.append(f"    count: {rows[name]['count']}")
        lines.append(f"    last: {rows[name]['last']}")
    return "\n".join(lines) + "\n"


def record(command):
    """Bump `command`'s row. Never raises."""
    try:
        vault_root = vaultlib.find_vault_root()
        path = vault_root / RECORD_FILE
        text = vaultlib.read_vault_text(path) if path.is_file() else ""
        since, rows = _parse(text)
        today = datetime.date.today().isoformat()
        since = since or today
        row = rows.setdefault(command, {"count": 0, "last": ""})
        row["count"] += 1
        row["last"] = today
        path.parent.mkdir(parents=True, exist_ok=True)
        vaultlib.write_text_lf(path, _render(since, rows))
    except Exception:
        pass


def run(args):
    import maincli

    vault_root = vaultlib.find_vault_root()
    path = vault_root / RECORD_FILE
    since, rows = _parse(vaultlib.read_vault_text(path)) if path.is_file() else (None, {})

    all_commands = [name for name, _ in maincli.COMMAND_SPECS]
    judgment, hooks, dead = [], [], []
    for name in all_commands:
        row = rows.get(name)
        if row is None or row["count"] == 0:
            dead.append(name)
        elif name in HOOK_COMMANDS:
            hooks.append((name, row))
        else:
            judgment.append((name, row))

    window = f"since {since}" if since else "no record yet"
    sys.stdout.write(f"compass usage ({window})\n")
    for name, row in sorted(judgment, key=lambda r: -r[1]["count"]):
        sys.stdout.write(f"  {name:20} {row['count']:6}  last {row['last']}\n")
    if hooks:
        sys.stdout.write("hook-fired entry points (harness traffic, not judgment):\n")
        for name, row in sorted(hooks, key=lambda r: -r[1]["count"]):
            sys.stdout.write(f"  {name:20} {row['count']:6}  last {row['last']}\n")
    if dead:
        sys.stdout.write(f"NEVER USED ({len(dead)}):\n")
        for name in dead:
            sys.stdout.write(f"  {name}\n")
    return 0
